<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" <?php if (empty($template)): ?> href="./assets/style.css" <?php else: ?>
            href="../assets/style.css" <?php endif ?>>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
    <title><?= $page_title ?></title>
    <style>

    </style>
</head>

<body>
    <div class="preloader">
        <div class="content-preloader">
            <?php if (empty($template)): ?>
                <img src="./assets/images/boycott.png" alt="boycott">
            <?php else: ?>
                <img src="../assets/images/boycott.png" alt="boycott">

            <?php endif ?>

        </div>
    </div>
    <nav class="navbar fixed-top">
        <div class="container">
            <?php if (empty($template)): ?>
                <a href="./index.php">
                <img src="./assets/images/boycott.png" class="logo" alt="boycott">
                </a>
            <?php else: ?>
                <a href="../index.php">
                <img src="../assets/images/boycott.png" class="logo" alt="boycott">
                </a>
            <?php endif ?>
            <?php if (session_status() != PHP_SESSION_NONE && array_key_exists('iduser', $_SESSION)): ?>
                <a href="./logout.php">
                    <button class="btn btn-outline-secondary">logout</button>
                </a>
            <?php else: ?>
                <div class="d-flex">
                    <a href="./login/">
                        <button class="btn btn-outline-secondary">Login</button>
                    </a>
                    <a href="./signup/" class="mx-2">
                        <button class="btn btn-outline-secondary">SignUp</button>
                    </a>

                </div>
            <?php endif; ?>
        </div>
    </nav>
    <?php if (empty($template) && !$show): ?>

        <div>

            <div class="section">
                <div class="text">
                    <p>Support Palestine. Boycott Israel
                    </p>
                    <p> Stand with the Palestinians in their struggle for freedom, justice, and equality. Whilst our
                        governments financially support the apartheid state, we don't have to.</p>
                    <a href="./ListCategory/">
                        <button class="btn btn-dark">
                            Browse Category
                        </button>
                    </a>
                </div>
            </div>
            <div class="container">
                <footer class="d-flex flex-wrap justify-content-between align-items-center my-4 border-top">
                    <div class="col-md-12 d-flex  justify-content-center align-items-center">
                        <span class="mb-3 mb-md-0 text-body-secondary">&copy; 2024 Boycott, Inc</span>
                    </div>
                </footer>
            </div>
        </div>
    <?php else: ?>

        <?php include $template . ".phtml" ?>
    <?php endif; ?>
</body>

<script <?php if (empty($template)): ?> src="./assets/main.js" <?php else: ?> src="../assets/main.js" <?php endif; ?>></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
    integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
    crossorigin="anonymous"></script>


</html>